base_url = "https://inlart.github.io"
compile_sass = true
build_search_index = true
title = "inlart"

taxonomies = [
    { name = "tags", feed = false},
    { name = "categories", feed = true },
]

[markdown]
highlight_code = true
external_links_target_blank = true

[extra]
